"""
ai/__init__.py — SENTINEL-FL AI package root.

Exposes top-level convenience imports so external code can do:
    from ai import Configuration, load_config, StructuredLogger
"""

from ai.fl_core import (
    Aggregator,
    AttackConfig,
    AttackReport,
    AttackSimulator,
    AuditReport,
    CheckpointNotFoundError,
    ClientUpdate,
    Configuration,
    ConfigValidationError,
    DatasetLoader,
    DatasetNotFoundError,
    DefenseStrategy,
    DetectionResult,
    Detector,
    EvaluationResult,
    Experiment,
    InsufficientCalibrationDataError,
    InsufficientClientsError,
    LogEntry,
    Logger,
    Metric,
    MetricsCollector,
    ModelMetadata,
    ModelRegistry,
    RemediationFailedError,
    ReversedTrigger,
    SentinelError,
    StructuredLogger,
    TrainingRound,
    TrustLedgerEntry,
    TrustScore,
    UnsupportedModelError,
    Visualizer,
    load_config,
    load_config_from_dict,
    make_logger,
)

__all__ = [
    "Aggregator",
    "AttackConfig",
    "AttackReport",
    "AttackSimulator",
    "AuditReport",
    "CheckpointNotFoundError",
    "ClientUpdate",
    "ConfigValidationError",
    "Configuration",
    "DatasetLoader",
    "DatasetNotFoundError",
    "DefenseStrategy",
    "DetectionResult",
    "Detector",
    "EvaluationResult",
    "Experiment",
    "InsufficientCalibrationDataError",
    "InsufficientClientsError",
    "LogEntry",
    "Logger",
    "Metric",
    "MetricsCollector",
    "ModelMetadata",
    "ModelRegistry",
    "RemediationFailedError",
    "ReversedTrigger",
    "SentinelError",
    "StructuredLogger",
    "TrainingRound",
    "TrustLedgerEntry",
    "TrustScore",
    "UnsupportedModelError",
    "Visualizer",
    "load_config",
    "load_config_from_dict",
    "make_logger",
]
